name: Telegram Scraper

on:
  schedule:
    - cron: '*/10 * * * *'   # هر ۱۰ دقیقه اجرا شود
  workflow_dispatch:         # امکان اجرای دستی از تب Actions
  push:                      # با هر push روی main/master
    branches:
      - main
      - master
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python main.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add soup.txt

          git diff --cached --quiet || git commit -m "Update soup.txt"

          git push
